include $(SND_TOPDIR)/toplevel.config
include $(SND_TOPDIR)/Makefile.conf

export-objs  := cs4231_lib.o cs4236_lib.o

isapnp-files := cs4232.isapnp cs4236.isapnp 

include $(SND_TOPDIR)/alsa-kernel/isa/cs423x/Makefile

include $(SND_TOPDIR)/Rules.make
