TOPDIR = ..

include $(TOPDIR)/toplevel.config
include $(TOPDIR)/Makefile.conf

export-objs  := util_mem.o

TOPDIR = $(MAINSRCDIR)
include $(TOPDIR)/alsa-kernel/synth/Makefile

include $(TOPDIR)/Rules.make
