TOPDIR = ../..

include $(TOPDIR)/toplevel.config
include $(TOPDIR)/Makefile.conf

#
#
#

TOPDIR = $(MAINSRCDIR)

snd-harmony-objs := harmony.o

# Toplevel Module Dependency
obj-$(CONFIG_SND_HARMONY) += snd-harmony.o

include $(TOPDIR)/Rules.make
