TOPDIR = ../..

include $(TOPDIR)/toplevel.config
include $(TOPDIR)/Makefile.conf

export-objs  := emux.o

TOPDIR = $(MAINSRCDIR)
include $(TOPDIR)/alsa-kernel/synth/emux/Makefile

include $(TOPDIR)/Rules.make
