TOPDIR = ../..

include $(TOPDIR)/toplevel.config
include $(TOPDIR)/Makefile.conf

#
#
#

TOPDIR = $(MAINSRCDIR)

snd-vx222-objs := vx222.o vx222_ops.o

obj-$(CONFIG_SND_VX222) += snd-vx222.o

include $(TOPDIR)/Rules.make
