TOPDIR = ../..

include $(TOPDIR)/toplevel.config
include $(TOPDIR)/Makefile.conf

export-objs = ak4xxx.o

TOPDIR = $(MAINSRCDIR)
include $(TOPDIR)/alsa-kernel/pci/ice1712/Makefile

include $(TOPDIR)/Rules.make
