#!/bin/bash

if [ -r /usr/share/aclocal/alsa-lib.m4 ]; then
  rm -f /usr/share/aclocal/alsa-lib.m4
fi
if [ -r /usr/local/share/aclocal/alsa-lib.m4 ]; then
  rm -f /usr/local/share/aclocal/alsa-lib.m4
fi
aclocal $ACLOCAL_FLAGS
autoconf
if [ $# -eq 0 ]; then
  echo "./configure --with-debug=full --with-isapnp=yes --with-sequencer=yes"
  ./configure --with-debug=full --with-isapnp=yes --with-sequencer=yes
else
  echo "./configure $@"
  ./configure $@
fi
make
