include $(SND_TOPDIR)/toplevel.config
include $(SND_TOPDIR)/Makefile.conf

#
#
#

snd-mixart-objs := mixart.o mixart_core.o mixart_hwdep.o mixart_mixer.o

obj-$(CONFIG_SND_MIXART) += snd-mixart.o

include $(SND_TOPDIR)/Rules.make
