TOPDIR = ../..

include $(TOPDIR)/toplevel.config
include $(TOPDIR)/Makefile.conf

export-objs  := ad1848_lib.o

TOPDIR = $(MAINSRCDIR)
include $(TOPDIR)/alsa-kernel/isa/ad1848/Makefile

include $(TOPDIR)/Rules.make
