TOPDIR = ..

include $(TOPDIR)/toplevel.config
include $(TOPDIR)/Makefile.conf

#
# ALSA extra code
#

extra-subdir-y	:= msnd
extra-subdir-m	:= $(extra-subdir-y)

#
#
#

TOPDIR = $(MAINSRCDIR)
include $(TOPDIR)/alsa-kernel/isa/Makefile
