TOPDIR = ../..

include $(TOPDIR)/toplevel.config
include $(TOPDIR)/Makefile.conf

export-objs  := es1688_lib.o

TOPDIR = $(MAINSRCDIR)
include $(TOPDIR)/alsa-kernel/isa/es1688/Makefile

include $(TOPDIR)/Rules.make
