TOPDIR = ../..

include $(TOPDIR)/toplevel.config
include $(TOPDIR)/Makefile.conf

export-objs += uda1341.o

TOPDIR = $(MAINSRCDIR)
include $(TOPDIR)/alsa-kernel/i2c/l3/Makefile

include $(TOPDIR)/Rules.make
