TOPDIR = ../..

include $(TOPDIR)/toplevel.config
include $(TOPDIR)/Makefile.conf

#
#
#

TOPDIR = $(MAINSRCDIR)

export-objs := vx_core.o

include $(TOPDIR)/alsa-kernel/drivers/vx/Makefile

include $(TOPDIR)/Rules.make

