TOPDIR = ../..

include $(TOPDIR)/toplevel.config
include $(TOPDIR)/Makefile.conf

export-objs += ak4xxx-adda.o

TOPDIR = $(MAINSRCDIR)
include $(TOPDIR)/alsa-kernel/i2c/other/Makefile

include $(TOPDIR)/Rules.make
