include $(SND_TOPDIR)/toplevel.config
include $(SND_TOPDIR)/Makefile.conf

export-objs  := ad1816a_lib.o

isapnp-files := ad1816a.isapnp

include $(SND_TOPDIR)/alsa-kernel/isa/ad1816a/Makefile

include $(SND_TOPDIR)/Rules.make
