include $(SND_TOPDIR)/toplevel.config
include $(SND_TOPDIR)/Makefile.conf

isapnp-files = wavefront.isapnp

SND_TOPDIR = $(MAINSRCDIR)
include $(SND_TOPDIR)/alsa-kernel/isa/wavefront/Makefile

include $(SND_TOPDIR)/Rules.make
