TOPDIR = ../..

include $(TOPDIR)/toplevel.config
include $(TOPDIR)/Makefile.conf

isapnp-files = wavefront.isapnp

TOPDIR = $(MAINSRCDIR)
include $(TOPDIR)/alsa-kernel/isa/wavefront/Makefile

include $(TOPDIR)/Rules.make
