TOPDIR = ../..

include $(TOPDIR)/toplevel.config
include $(TOPDIR)/Makefile.conf

#
#
#

export-objs = vx_entry.o

TOPDIR = $(MAINSRCDIR)
include $(TOPDIR)/alsa-kernel/pcmcia/vx/Makefile

include $(TOPDIR)/Rules.make
