ifndef SND_TOPDIR
SND_TOPDIR=../..
endif

include $(SND_TOPDIR)/toplevel.config
include $(SND_TOPDIR)/Makefile.conf

snd-riptide-objs := riptide.o

obj-$(CONFIG_SND_RIPTIDE) += snd-riptide.o

include $(SND_TOPDIR)/Rules.make
