#!/bin/sh

# This script is intended to be used AFTER moving this
# source code files into the alsa-kernel/ directory
# to create the .c and .h stub files for THIS directory.
# It was written for the alsa-driver tarball. If aplied
# to the CVS tree, you may need add another "../"
# on the include path.

FILES=$(ls -1 -A $1/*.c $1/*.h)

for file in $FILES
do
  fil=$(basename $file)
  echo $file -- $fil
  echo "#define __NO_VERSION__" > $fil
  echo "#include \"../../alsa-kernel/pci/au88x0/$fil\"" >> $fil
  echo >> $fil
done

