#!/bin/sh
#
# setup alsa-kernel directory from an external linux kernel tree
#
# the linux kernel tree has to contain the latest alsa-kernel files
# (this script doesn't check the consistency)
#

if [ -z "$1" ]; then
    echo "usage: make-alsa-kernel kernel-tree-dir"
    exit 1
fi

if [ ! -d acore ]; then
    echo "Run this script on alsa-driver directory"
    exit 1
fi

kern="$1"
alsa=$(pwd)
rm -f $alsa/linux
ln -s $kern linux

rm -rf alsa-kernel
mkdir alsa-kernel
cd $kern/sound
for i in *; do
   ln -s ../linux/sound/$i $alsa/alsa-kernel/$i
done
ln -s ../linux/include/sound $alsa/alsa-kernel/include
ln -s ../linux/Documentation/sound/alsa $alsa/alsa-kernel/Documentation
ln -s ../linux/scripts $alsa/alsa-kernel/scripts
exit 0
