#!/bin/sh
#
# setup alsa-kernel directory from an external linux kernel tree
#
# the linux kernel tree has to contain the latest alsa-kernel files
# (this script doesn't check the consistency)
#

if [ -z "$1" ]; then
    echo "usage: make-alsa-kernel kernel-tree-dir"
    exit 1
fi

kern="$1"
alsa=$(pwd)
case $kern in
/*)
    ;;
*)
    cd $kern
    kern=$(pwd)
    cd $alsa
    ;;
esac
rm -rf alsa-kernel
mkdir alsa-kernel
cd $kern/sound
for i in *; do
   ln -s $kern/sound/$i $alsa/alsa-kernel
done
ln -s $kern/include/sound $alsa/alsa-kernel/include
ln -s $kern/Documentation/sound/alsa $alsa/alsa-kernel/Documentation
ln -s $kern/scripts $alsa/alsa-kernel/scripts
exit 0
