#!/bin/sh

if [ -x ./snd-deps ]
then
	./snd-deps --acinclude > ../acinclude.m4
	./snd-deps --makefile > ../cards.config.in
	./snd-deps --cinclude > ../include/config1.h.in
else
	echo "Cannot execute ./snd-deps"
fi
