ifndef SND_TOPDIR
SND_TOPDIR=..
endif

include $(SND_TOPDIR)/toplevel.config
include $(SND_TOPDIR)/Makefile.conf

obj-$(CONFIG_SND) += pdaudiocf/

include $(SND_TOPDIR)/alsa-kernel/pcmcia/Makefile

include $(SND_TOPDIR)/Rules.make


