TOPDIR = ..

include $(TOPDIR)/toplevel.config
include $(TOPDIR)/Makefile.conf

#
#
#

TOPDIR = $(MAINSRCDIR)

obj-$(CONFIG_SND) += pdaudiocf/

include $(TOPDIR)/alsa-kernel/pcmcia/Makefile

include $(TOPDIR)/Rules.make


